=== alvarobarrena02/hito-individual-LM/pedidos.dtd
<!ELEMENT clientes (pedidos)*> <!-- define un elemento clientes que puede contener cero o más elementos pedidos -->
<!ELEMENT pedidos (trimestre)*> <!-- define un elemento pedidos que puede contener cero o más elementos trimestre -->
<!ATTLIST pedidos
        año CDATA #REQUIRED> <!-- define un atributo año del elemento pedidos como requerido y de tipo CDATA -->
<!ELEMENT trimestre (pedido)*> <!--  define un elemento trimestre que puede contener cero o más elementos pedido -->
<!ATTLIST trimestre
        trimestre CDATA #REQUIRED> <!-- define un atributo trimestre del elemento trimestre como requerido y de tipo CDATA -->
<!ELEMENT pedido (nombre|apellidos|telefono|direccion|correo_electronico|fecha_inclusion|numero_pedido|fecha_compra|fecha_entrega|total_factura|productos)*> <!-- define un elemento pedido que puede contener cualquiera de los elementos especificados en el paréntesis, en cualquier orden y cantidad, incluyendo cero. -->
<!ELEMENT nombre (#PCDATA)> <!-- define un elemento nombre que solo puede contener texto (PCDATA) -->
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle|ciudad|codigo_postal|provincia)*> <!-- define un elemento direccion que puede contener cualquiera de los elementos especificados en el paréntesis, en cualquier orden y cantidad, incluyendo cero -->
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT correo_electronico (#PCDATA)>
<!ELEMENT fecha_inclusion (#PCDATA)>
<!ELEMENT numero_pedido (#PCDATA)>
<!ELEMENT fecha_compra (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT total_factura (#PCDATA)>
<!ELEMENT productos (producto)*>
<!ELEMENT producto (nombre_producto|referencia|unidades|precio)*>
<!ELEMENT nombre_producto (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

=== alvarobarrena02/hito-individual-LM/pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "pedidos.dtd">
<clientes>
    <pedidos año="2021">
        <trimestre trimestre="1">
            <!-- Detalle de los 10 pedidos -->
            <!-- Pedido 1 -->
            <pedido>
                <nombre>Antonio</nombre>
                <apellidos>García López</apellidos>
                <telefono>645236147</telefono>
                <direccion>
                    <calle>La Fontanilla 72</calle>
                    <ciudad>Peñarroya/pueblonuevo</ciudad>
                    <codigo_postal>14200</codigo_postal>
                    <provincia>Córdoba</provincia>
                </direccion>
                <correo_electronico>antonio.garcia@gmail.com</correo_electronico>
                <fecha_inclusion>05/02/2021</fecha_inclusion>
                <numero_pedido>1</numero_pedido>
                <fecha_compra>10/02/2021</fecha_compra>
                <fecha_entrega>12/02/2021</fecha_entrega>
                <total_factura>7500€</total_factura>
                <productos>
                    <producto>
                        <nombre_producto>Altavoces</nombre_producto>
                        <referencia>SD190</referencia>
                        <unidades>50</unidades>
                        <precio>150€</precio>
                    </producto>
                </productos>
            </pedido>
            <!-- Pedido 2 -->
            <pedido>
                <nombre>María</nombre>
                <apellidos>Ruiz López</apellidos>
                <telefono>698741236</telefono>
                <direccion>
                    <calle>Prolongación San Sebastian 55</calle>
                    <ciudad>Cala</ciudad>
                    <codigo_postal>21270</codigo_postal>
                    <provincia>Hueva</provincia>
                </direccion>
                <correo_electronico>maria.ruiz@gmail.com</correo_electronico>
                <fecha_inclusion>02/01/2021</fecha_inclusion>
                <numero_pedido>2</numero_pedido>
                <fecha_compra>09/01/2021</fecha_compra>
                <fecha_entrega>12/01/2021</fecha_entrega>
                <total_factura>1200€</total_factura>
                <productos>
                    <producto>
                        <nombre_producto>Monitores</nombre_producto>
                        <referencia>MT786</referencia>
                        <unidades>6</unidades>
                        <precio>200€</precio>
                    </producto>
                </productos>
            </pedido>
            <!-- Pedido 3 -->
            <pedido>
                <nombre>Ana</nombre>
                <apellidos>Pérez Castro</apellidos>
                <telefono>63321455</telefono>
                <direccion>
                    <calle>Calle Mayor 12</calle>
                    <ciudad>Madrid</ciudad>
                    <codigo_postal>28003</codigo_postal>
                    <provincia>Madrid</provincia>
                </direccion>
                <correo_electronico>ana.perez@gmail.com</correo_electronico>
                <fecha_inclusion>12/01/2021</fecha_inclusion>
                <numero_pedido>3</numero_pedido>
                <fecha_compra>16/01/2021</fecha_compra>
                <fecha_entrega>25/01/2021</fecha_entrega>
                <total_factura>3500€</total_factura>
                <productos>
                    <producto>
                        <nombre_producto>Auriculares</nombre_producto>
                        <referencia>AU158</referencia>
                        <unidades>70</unidades>
                        <precio>50€</precio>
                    </producto>
                </productos>
            </pedido>
            <!-- Pedido 4 -->
            <pedido>
                <nombre>Pedro</nombre>
                <apellidos>Sánchez Ortiz</apellidos>
                <telefono>625784321</telefono>
                <direccion>
                    <calle>Avenida del Mar 24</calle>
                    <ciudad>Málaga</ciudad>
                    <codigo_postal>29012</codigo_postal>
                    <provincia>Málaga</provincia>
                </direccion>
                <correo_electronico>pedro.sanchez@gmail.com</correo_electronico>
                <fecha_inclusion>01/01/2021</fecha_inclusion>
                <numero_pedido>4</numero_pedido>
                <fecha_compra>05/01/2021</fecha_compra>
                <fecha_entrega>10/01/2021</fecha_entrega>
                <total_factura>800€</total_factura>
                <productos>
                    <producto>
                        <nombre_producto>Memoria RAM 32GB</nombre_producto>
                        <referencia>RM320</referencia>
                        <unidades>4</unidades>
                        <precio>200€</precio>
                    </producto>
                </productos>
            </pedido>
            <!-- Pedido 5 -->
            <pedido>
                <nombre>Domingo</nombre>
                <apellidos>Martínez López</apellidos>
                <telefono>622114400</telefono>
                <direccion>
                    <calle>Calle Alcalá 42</calle>
                    <ciudad>Madrid</ciudad>
                    <codigo_postal>28052</codigo_postal>
                    <provincia>Madrid</provincia>
                </direccion>
                <correo_electronico>domingo.martinez@gmail.com</correo_electronico>
                <fecha_inclusion>02/01/2021</fecha_inclusion>
                <numero_pedido>5</numero_pedido>
                <fecha_compra>28/01/2021</fecha_compra>
                <fecha_entrega>14/02/2021</fecha_entrega>
                <total_factura>2500€</total_factura>
                <productos>
                    <producto>
                        <nombre_producto>iPhone 14 Pro</nombre_producto>
                        <referencia>IP145</referencia>
                        <unidades>1</unidades>
                        <precio>2500€</precio>
                    </producto>
                </productos>
            </pedido>
            <!-- Pedido 6 -->
            <pedido>
                <nombre>David</nombre>
                <apellidos>Fernández Díaz</apellidos>
                <telefono>625678901</telefono>
                <direccion>
                    <calle>Plaza Mayor 5</calle>
                    <ciudad>Salamanca</ciudad>
                    <codigo_postal>37002</codigo_postal>
                    <provincia>Salamanca</provincia>
                </direccion>
                <correo_electronico>david.fernandez@gmail.com</correo_electronico>
                <fecha_inclusion>02/01/2021</fecha_inclusion>
                <numero_pedido>6</numero_pedido>
                <fecha_compra>28/01/2021</fecha_compra>
                <fecha_entrega>14/02/2021</fecha_entrega>
                <total_factura>1500€</total_factura>
                <productos>
                    <producto>
                        <nombre_producto>Cámara Canon</nombre_producto>
                        <referencia>CA513</referencia>
                        <unidades>3</unidades>
                        <precio>500€</precio>
                    </producto>
                </productos>
            </pedido>
            <!-- Pedido 7 -->
            <pedido>
                <nombre>María</nombre>
                <apellidos>Jiménez Frías</apellidos>
                <telefono>655424556</telefono>
                <direccion>
                    <calle>Calle San Bernardo 32</calle>
                    <ciudad>Sevilla</ciudad>
                    <codigo_postal>41625</codigo_postal>
                    <provincia>Sevilla</provincia>
                </direccion>
                <correo_electronico>maria.jimenez@gmail.com</correo_electronico>
                <fecha_inclusion>06/01/2021</fecha_inclusion>
                <numero_pedido>7</numero_pedido>
                <fecha_compra>05/01/2021</fecha_compra>
                <fecha_entrega>20/01/2021</fecha_entrega>
                <total_factura>1000€</total_factura>
                <productos>
                    <producto>
                        <nombre_producto>Xiaomi 11T</nombre_producto>
                        <referencia>XT117</referencia>
                        <unidades>2</unidades>
                        <precio>500€</precio>
                    </producto>
                </productos>
            </pedido>
            <!-- Pedido 8 -->
            <pedido>
                <nombre>Antonio</nombre>
                <apellidos>Alonso García</apellidos>
                <telefono>622114400</telefono>
                <direccion>
                    <calle>Calle Alcalá 42</calle>
                    <ciudad>Madrid</ciudad>
                    <codigo_postal>28052</codigo_postal>
                    <provincia>Madrid</provincia>
                </direccion>
                <correo_electronico>antonio.alonso@gmail.com</correo_electronico>
                <fecha_inclusion>02/01/2021</fecha_inclusion>
                <numero_pedido>8</numero_pedido>
                <fecha_compra>28/01/2021</fecha_compra>
                <fecha_entrega>14/02/2021</fecha_entrega>
                <total_factura>1500€</total_factura>
                <productos>
                    <producto>
                        <nombre_producto>Portátil HP</nombre_producto>
                        <referencia>PH117</referencia>
                        <unidades>1</unidades>
                        <precio>1500€</precio>
                    </producto>
                </productos>
            </pedido>
            <!-- Pedido 9 -->
            <pedido>
                <nombre>Olga</nombre>
                <apellidos>Barriuso Ausín</apellidos>
